### ISSUE TITLE
Vorlesungsfolien aus WS 2019/2020

### ISSUE THREAD

**Issue by tpuddu** [irgroup/dis12-2020#1]
Die hochgeladenen Vorlesungsfolien sind aus dem letzten Wintersemester, dadurch stimmen die jeweiligen Datumsangaben etc. nicht.

**Comment by phschaer** [comment]
Stimmt! :-)

Ist bis Freitag behoben. Die Inhalte bleiben aber gleich. Nur das Organisatorische passe ich noch an.

**Comment by phschaer** [comment]
#fixed
