### ISSUE TITLE
Fehlerhafte Verlinkung Exercise Web Crawling + Link Analysis

### ISSUE THREAD

**Issue by ls0218** [irgroup/dis12-2020#4]
Guten Tag Herr Schaer,

wenn ich auf Exercise Web Crawling + Link Analysis in der Readme-Datei in der Tabelle klicke, wird mir die Übung 05 angezeigt. 

Könnten Sie dies bitte überprüfen?

Vielen Dank im Voraus.

Mit freundlichen Grüßen
Leonie Schulz

**Comment by phschaer** [comment]
fixed in 9a209cf

Danke für den Hinweis.
